<div class="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Anmeldeinformationen bearbeiten</h4>
            </div>
            <div id="message"></div>
            <?php
            $this->form->prepare();
            echo $this->form()->openTag($this->form);
            ?>
            <div class="modal-body">
                <?php
                foreach ($this->form as $element)
                {
                    if (!($element instanceof Zend\Form\Element\Submit))
                    {
                        echo '<div class="form-group">';
                        $label = $element->getOption('label');
                        echo $this->formLabel()->openTag() . $label . $this->formLabel()->closeTag();
                        echo $this->formElementErrors($element);
                        $element->setAttribute('class', 'form-control');
                        $element->setAttribute('placeholder', $label);
                        echo $this->formElement($element);
                        echo '</div>';
                    }
                }
                ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Schliessen</button>
                <button type="button" class="btn btn-default" onclick="validateForm('editUserForm');">Speichern</button>
            </div>
            <?php echo $this->form()->closeTag($this->form); ?>
        </div>
    </div>
</div>