<div class="modal" id="editUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Anmeldeinformationen bearbeiten</h4>
            </div>
            <div id="errormessage"></div>
            <?php echo $this->content; ?>
        </div>
    </div>
</div>