<div class="container">
<h2>Avatar ändern</h2>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'));
$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
?>

<div class="row ">
    <div class="row-same-height">

        <div class="col-xs-4">
            <img src="<?php echo $this->avatarUrl; ?>" alt="avatar" />
        </div>
        <div class="col-xs-6 col-xs-height col-top">
            <?php
            $this->form->setAttribute('action', $this->uploadAvatar);
            $this->form->setAttribute('enctype', 'multipart/form-data');
            $this->form->prepare();

            echo $this->form()->openTag($this->form);
            foreach ($this->form as $element) {
                if ($element instanceof Zend\Form\Element\Submit) {
                    echo '<div>';
                    $element->setAttribute('class', 'btn btn-primary');
                    $element->setAttribute('style', 'float: left; margin-right: 17px;');
                } else {
                    echo '<div class="form-group">';
                    $label = $element->getOption('label');
                    echo $this->formLabel()->openTag() . $label . $this->formLabel()->closeTag();
                    echo $this->formElementErrors($element);
                    $element->setAttribute('class', 'btn btn-default btn-file');
                }
                echo $this->formElement($element);
                echo '</div>';
            }
            echo $this->form()->closeTag($this->form);
            ?>

            <a class="btn btn-default" href="<?php echo $this->closeUrl; ?>">Schliessen</a>
        </div>
    </div>
</div>
</div>