<h2 class="form-signin-heading">Bitte einloggen</h2>

<?php if ($this->loginMessage): ?>
    <div class="alert alert-warning">
        <a class="close" data-dismiss="alert" href="#">×</a><?php echo $this->loginMessage; ?>
    </div>
<?php endif ?>

<div class="row">
    <div class="col-xs-6">
        <?php
        $this->loginForm->setAttribute('action', $this->url('user'));
        $this->loginForm->prepare();
        echo $this->form()->openTag($this->loginForm);
        foreach ($this->loginForm as $element)
        {
            if ($element instanceof Zend\Form\Element\Submit)
            {
                echo '<div>';
                $element->setAttribute('class', 'btn btn-primary');
            } else
            {
                echo '<div class="form-group">';
                $label = $element->getOption('label');
                echo $this->formLabel()->openTag() . $label . $this->formLabel()->closeTag();
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $label);
            }
            echo $this->formElement($element);

            echo '</div>';
        }
        echo $this->form()->closeTag($this->loginForm);
        ?>
    </div>
</div>