<h2 class="form-signin-heading">Bitte einloggen</h2>

<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->renderCurrent('info', array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'));
$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();

echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<div class="row">
    <div class="col-xs-6">
        <?php
        $this->form->setAttribute('action', $this->url('user'));
        $this->form->prepare();
        echo $this->form()->openTag($this->form);
        foreach ($this->form as $element)
        {
            if ($element instanceof Zend\Form\Element\Submit)
            {
                echo '<div>';
                $element->setAttribute('class', 'btn btn-primary');
            } else
            {
                echo '<div class="form-group">';
                $label = $element->getOption('label');
                echo $this->formLabel()->openTag() . $label . $this->formLabel()->closeTag();
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $label);
            }
            echo $this->formElement($element);

            echo '</div>';
        }
        echo $this->form()->closeTag($this->form);
        ?>
    </div>
</div>