<h1>Benutzer verwalten</h1>

<table class="table">
    <tr>
        <th>Anzeigename</th>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>Identität</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($this->users as $user) : ?>

        <tr>
            <td><?php echo $this->escapeHtml($user->getDisplayName()); ?></td>
            <td><?php echo $this->escapeHtml($user->getFirstname()); ?></td>
            <td><?php echo $this->escapeHtml($user->getLastname()); ?></td>
            <td><?php echo $this->escapeHtml($user->getIdentity()); ?></td>
            <td>
                <a href="<?php echo $this->url('user/manage/edit', array('id' => $user->getId())); ?>">Bearbeiten</a>
                <a href="<?php echo $this->url('user/manage/delete', array('id' => $user->getId())); ?>">Löschen</a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>