<script type="text/javascript">
    var urlform = '<?php echo $this->url('user/profile'); ?>';
</script>

<?php
$user = $this->userIdentity();
$personal = $user->getPersonal();

if ($this->runModal)
{
    $script = "$( document ).ready(function() {" .
            "$('#$this->runModal').modal('show');" .
            "});";

    $this->inlineScript()->appendScript($script);
}
?>

<div class="page-header">
    <h1>Mein Benutzerprofil</h1>
</div>

<p class="lead">
    <img src="<?php echo $this->basePath() . '/user/avatar' ?>" 
         alt="avatar"  style="float:left;" />
         <?php echo $user->getIdentity(); ?>
</p>
<button type="button" class="btn btn-default" onclick="showForm('\\user\\edit');">Profil bearbeiten</button>
<br>
<a class="btn btn-default" href="/user/editavatar">Avatar ändern</a>
<p style="clear: both;" />

<h2>Persönliche Angaben</h2>
<p class="lead">
    <?php echo $personal->getFirstname() . ' ' . $personal->getLastname(); ?><br>
    <?php echo $personal->getStreetAndNr(); ?><br>
    <?php echo $personal->getPostalCode() . ' ' . $personal->getCity(); ?><br><br>
    Telefon: <?php echo $personal->getPhone(); ?>
</p>

<div id="profilemodal"></div>
