<?php
$user = $this->userIdentity();
$personal = $user->getPersonal();

if ($this->runModal)
{
    $script = "$( document ).ready(function() {" .
            "$('#$this->runModal').modal('show');" .
            "});";
    
    $this->inlineScript()->appendScript($script);
}
?>

<div class="page-header">
    <h1>Mein Benutzerprofil</h1>
</div>

<p class="lead">
    <img src="<?php echo $this->basePath() . '/img/avatar-placeholder.jpg' ?>" 
         alt="avatar placeholder"  style="float:left;" />
         <?php echo $user->getIdentity(); ?>
</p>
<button type="button" class="btn btn-default" onclick="$('#editUserModal').modal('show');">Bearbeiten</button>
<p style="clear: both;" />

<h2>Persönliche Angaben</h2>
<p class="lead">
    <?php echo $personal->getFirstname() . ' ' . $personal->getLastname(); ?><br>
    <?php echo $personal->getStreetAndNr(); ?><br>
    <?php echo $personal->getPostalCode() . ' ' . $personal->getCity(); ?><br><br>
    Telefon: <?php echo $personal->getPhone(); ?>
</p>

<?php echo $this->editUserModal; ?>