<h2>Registrieren</h2>

<?php
$this->registerForm->setAttribute('action', $this->url('user'));
$this->registerForm->setAttribute('class', 'form-signin');
$this->registerForm->setAttribute('enctype', 'multipart/form-data');
$this->registerForm->prepare();

echo $this->form()->openTag($this->registerForm);
foreach ($this->registerForm->get('user-fieldset') as $element)
{
    if ($element instanceof Zend\Form\Element\Submit)
    {
        $element->setAttribute('class', 'btn btn-lg btn-primary btn-block');
    } else
    {
        $label = $element->getOption('label');
        echo $this->formLabel()->openTag() . $label . $this->formLabel()->closeTag();
        $element->setAttribute('class', 'form-control');
        $element->setAttribute('placeholder', $label);
    }
    echo $this->formElement($element) . '<br>';
}
echo $this->form()->closeTag($this->registerForm);
