<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/user.js')
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Badenfahrt</a>
                </div>
                <div class="collapse navbar-collapse">               
                    <ul class="nav navbar-nav">
                        <li><a href=" <?php echo $this->url('home') ?>">Start</a></li>
                        <?php
                        if ($this->userIdentity())
                        {
                            // TODO: Problem with url helper (action).
                            echo '<li><a href="' . $this->url('user') . '\logout">Logout</a></li>';
                        } else
                        {
                            echo '<li><a href="' . $this->url('user') . '">Login</a></li>';
                            echo '<li><a href="' . $this->url('user') . '\register">Registrieren</a></li>';
                        }
                        if ($this->isAllowed('\User\Model\User', 'edit'))
                        {
                            // TODO: Problem with url helper (action).
                            echo '<li><a href="' . $this->url('user') . '\edit">Profil</a></li>';
                        }
                        if ($this->isAllowed('\User\Model\User', 'manage'))
                        {
                            // TODO: Problem with url helper (action).
                            echo '<li><a href="' . $this->url('user') . '\manage">Benutzer</a></li>';
                        }
                        ?>
                    </ul>
                    <?php if ($this->userIdentity()): ?>
                        <div class="navbar-text navbar-right">Eingeloggt als 
                            <?php echo $this->userIdentity()->getDisplayName() ?> 
                        </div>
                    <?php endif; ?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. </p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
