<div class="container">
<hr>
<div class="jumbotron">
	<div class="row clearfix">
         
		<div class="col-md-12 column">
                    <div class="row">
                        <div class="pull-left">
                            <h2 class="text-left">
				Registrierte Benutzer
                            </h2>
                        </div>
                    <div class="pull-right">
                    <button value="" onclick="" name="detailBTN" type="button" class="btn btn-info">Details</button>
                    <button value="" onclick="" name="setpwdBTN" type="button" class="btn btn-warning">Passwort Setzen</button>
                    <button value="" onclick="" name="deleteBTN" type="button" class="btn btn-danger">Löschen</button>
                    </div>
                    </div>
			<table class="table">
				<thead>
					<tr>
						<th>
							Name
						</th>
						<th>
							bewerbung platz
						</th>
						<th>
							Name / Verein
						</th>
                                                <th>
							Auswahl
						</th>
					</tr>
				</thead>
				<tbody>
					<tr class="active">
						<td>
							Giacomo Guilizzoni Founder & CEO
						</td>
						<td>
							37
						</td>
                                                <td>
							Peldi
						</td>
						<td>
							<input type="checkbox" value="" checked>
						</td>
					</tr>
					<tr class="">
						<td>
							Marco Botton Tuttofare
						</td>
						<td>
							34
						</td>
						<td>
							
						</td>
                                                <td>
							<input type="checkbox" value="">
						</td>
					</tr>
					
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>