<!--
<div class="container">
    <hr>
-->      
<!--
<h2>Registrieren</h2>
-->
<div class="jumbotron">
    <!--
    <h2>Registrieren</h2>
    -->

    <div id="wrap" class="container">
        <div class="row">
            <div class="col-md-12">

                <form id="register" class="form" enctype="multipart/form-data" name="register" method="post" action="/user/register">
                    <div class="row">
                        <div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="Name / Verein" required="required" name="nameInput">
                        </div>

                        <div class="col-xs-8 col-md-6">
                            <!-- Img  durch std Profil ersetzen -->
                            <img alt="140x140" src="http://lorempixel.com/140/140/" />
                            <input id="profileInputFile" type="file" />
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="Vorname" required="required" name="firstNameInput">
                        </div>
                        <div class="col-xs-6 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="Nachname" required="required" name="lastNameInput">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="Strasse, Nr" required="required" name="streetInput">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="PLZ" required="required" name="plzInput">
                        </div>
                        <div class="col-xs-6 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="Ort" required="required" name="cityInput">
                        </div>
                    </div>    


                    <div class="row">
                        <div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="text" value="" placeholder="TelNr." required="required" name="telnoInput">
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="email" value="" placeholder="E-Mail" required="required" name="emailInput">
                        </div>
						
						<div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="password" value="" placeholder="Gewünschtes Passwort" required="required" name="passwordInput">
                        </div>
						
						<div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="password" value="" placeholder="Passwort bestätigen" required="required" name="passwordVerifyInput">
                        </div>
                    </div>

                    <div class="row">
                        <!--
						<div class="col-xs-8 col-md-6">
                            <input class="form-control input-lg" type="email" value="" placeholder="E-Mail bestätigen" required="required" name="emailConfirm">
                        </div>
                        -->
						<br>
						
                        <input class="btn btn btn-success btn-lg pull-right" type="submit" value="Änderungen übernehmen" name="submit">
						<input class="btn btn btn-success btn-lg pull-left" type="submit" value="Anmeldung zurückziehen" name="submit">
                    </div>



                    <!-- Könnt man noch als Sicherheit gegen Bots ...
                    <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <input class="form-control input-lg" type="hidden" value="16a58a1730dbe94d9d72ba9abc2fcf8d" placeholder="Verify you are human" required="required" name="hiddenInput">
                        </div>
                    </div>
                    -->

                    <!-- Alternativen für buttons                
                    <div class="row">
                        <div class="col-sm-12">
                       
                                <input class="btn btn btn-success btn-lg" type="submit" value="Abschicken" name="submit">
                                <button class="btn btn btn-success btn-lg pull-right" value="" onclick="window.location =&quot;/user/register&quot;" name="login" type="button">Abschicken</button>
                        </div>
                    </div>
                    -->

                    <!-- Könnt man noch als Sicherheit gegen Bots Ver2...
                        <input type="hidden" value="22840dd81fae4088fd6aeeb478ae1f67-d0c09b0b4905b733beacee841db62208" name="csrfInput">
                    -->
                </form>
            </div>
        </div>
    </div>
</div>
<!--
</div>
-->
