<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h1>
				FAQ
			</h1>
			<div class="panel-group" id="panel-316218">
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-316218" href="#panel-element-255132">Bis wann läuft die Anmeldefrist?</a>
					</div>
					<div id="panel-element-255132" class="panel-collapse collapse">
						<div class="panel-body">
							Sie können sich bis 10. Februar 15 anmelden. Bis 1. März werden sie informiert ob sie den zuschlag bekommen haben.
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-316218" href="#panel-element-22991">Was sind die Kosten?</a>
					</div>
					<div id="panel-element-22991" class="panel-collapse collapse">
						<div class="panel-body">
							Die Kosten Berechnen sich pro Quadratmeter Fläche und Sitzplatz. Satz pro m^2 und Sitzplatz 50.- pro Tag.
						</div>
					</div>
					
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-316218" href="#panel-element-22991">Ich habe mein Passwort vergessen.</a>
					</div>
					<div id="panel-element-22991" class="panel-collapse collapse">
						<div class="panel-body">
							Bitte benutzen Sie Die Passwort vergessen Funktion. Falls sie immer noch Probleme haben, melden Sie sich bitte über Kontaktformular.
						</div>
					</div>
				</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						 <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-316218" href="#panel-element-22991">Ich kenne Smuel Egger, habe ich Rabatt?</a>
					</div>
					<div id="panel-element-22991" class="panel-collapse collapse">
						<div class="panel-body">
							Nur zu den üblichen Eggerschen bedingungen. Ihre 1. Tochter gehört beim Erreichen des 18. Lebensalters S. Egger.
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>