<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="jumbotron">
				<h1>
					Badenfahrt Teilnehmerportal
				</h1>
				<p>
					Kurz-Info zu den Möglichkeiten
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row clearfix">
		<div class="col-md-4 column">
			<h2>
				Festwirtschaft
			</h2>
			<p>
				Was bringt den ABB-Lehrling dazu, jeden Abend nach Arbeitsschluss zu hämmern, zu sägen und zu schrauben, bis die Festbeiz steht? Warum opfern die Mitglieder des Quartiervereins Ferientage, um Theaterstücke einzuüben? Wie ist es möglich, dass eine Stadt mit 18 000 Einwohnern ein zehntägiges Fest auf die Beine stellt, mit 70 liebevollen Beizen und Hunderten von kulturellen Acts – ein Fest, das fast eine Million Menschen anziehen wird?
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p><img alt="140x140" src="http://lorempixel.com/140/140/" class="img-rounded" />
		</div>
		<div class="col-md-4 column">
			<h2>
				Feststand
			</h2>
			<p>
				Was bringt den ABB-Lehrling dazu, jeden Abend nach Arbeitsschluss zu hämmern, zu sägen und zu schrauben, bis die Festbeiz steht? Warum opfern die Mitglieder des Quartiervereins Ferientage, um Theaterstücke einzuüben? Wie ist es möglich, dass eine Stadt mit 18 000 Einwohnern ein zehntägiges Fest auf die Beine stellt, mit 70 liebevollen Beizen und Hunderten von kulturellen Acts – ein Fest, das fast eine Million Menschen anziehen wird?
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p><img alt="140x140" src="http://lorempixel.com/140/140/" class="img-rounded" />
		</div>
		<div class="col-md-4 column">
			<h2>
				Gastrobetrieb
			</h2>
			<p>
				Was bringt den ABB-Lehrling dazu, jeden Abend nach Arbeitsschluss zu hämmern, zu sägen und zu schrauben, bis die Festbeiz steht? Warum opfern die Mitglieder des Quartiervereins Ferientage, um Theaterstücke einzuüben? Wie ist es möglich, dass eine Stadt mit 18 000 Einwohnern ein zehntägiges Fest auf die Beine stellt, mit 70 liebevollen Beizen und Hunderten von kulturellen Acts – ein Fest, das fast eine Million Menschen anziehen wird?
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p><img alt="140x140" src="http://lorempixel.com/140/140/" class="img-rounded" />
		</div>
	</div>
</div>