<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="jumbotron">
                <h1>
                    Badenfahrt Teilnehmer Portal
                </h1>
                <p>
                    Curabitur sed lobortis augue, nec interdum turpis. Nulla ultricies, ipsum hendrerit venenatis auctor, ex arcu sodales quam, id pharetra mauris mauris a magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam tristique, erat pharetra consequat bibendum, quam nisi convallis libero, id tempor diam mi ut tellus. Suspendisse sagittis, enim sed interdum feugiat, sem ipsum auctor tortor, ac cursus turpis mi at elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut fringilla elit in turpis ornare viverra. Maecenas quam ipsum, aliquet sed elit at, euismod luctus magna. Praesent viverra elit ac ornare dignissim. Suspendisse in neque non ante tempus iaculis. Praesent vehicula nec metus eu dignissim. Nullam vel iaculis augue. Aenean lectus lectus, pellentesque vel erat eget, varius congue tellus. Vestibulum quis dolor lacinia, faucibus nisl id, commodo purus. 
                </p>
                <p>
                    
                </p>
                <p>
                    <a class="btn btn-primary btn-large" href="#info">Mehr Informationen</a>
                </p>
            </div>
        </div>
    </div>
    <div id="info" class="container">
        <div class="row clearfix">
            <div id="Festwirtschaft" class="col-md-4 column">
                <h2>
                    Festwirtschaft
                </h2>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pharetra nibh vel purus pretium, ut aliquam sem tincidunt. Quisque ut tempus lorem. Phasellus commodo mi at interdum placerat. Pellentesque ut nulla mauris. Vestibulum eu massa consectetur, porttitor magna quis, fringilla leo. Suspendisse tellus augue, tincidunt at ullamcorper vel, ornare in sem. Aliquam venenatis risus ex, sit amet laoreet libero viverra ac. Proin quis ligula in urna tempor rutrum. Nullam a dictum mauris, id eleifend nulla. In hac habitasse platea dictumst. Ut fermentum velit vel quam dignissim, in cursus turpis consectetur. Etiam vitae odio nec ligula vehicula maximus. 
                </p>
                <p>
                    <!-- ToDo: Am Ende kann hir auf eine extra seite verwiesen Werden -->
                    <a class="btn" href="#Festwirtschaft">Mehr dazu</a>
                </p><img src="http://lorempixel.com/140/140/cats" alt="Bsp. Bild 140x140" class="img-rounded" />
            </div>

            <div id="Feststand" class="col-md-4 column">
                <h2>
                    Feststand
                </h2>
                <p>
                    Quisque porttitor efficitur odio. Duis et magna nec nisi viverra congue. Curabitur sit amet pellentesque sapien. Quisque dictum ac diam vitae consectetur. Aliquam in diam pulvinar, malesuada sapien sit amet, aliquet orci. Integer et enim at dui scelerisque gravida ut vitae nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam lacinia dui a mi cursus finibus quis eu ante. Curabitur id mi sit amet tellus feugiat cursus ac dictum risus. Vivamus dignissim eros sit amet commodo pulvinar. Morbi a euismod tellus. Praesent at venenatis dolor.
                </p>
                <p>
                    Mauris gravida pulvinar risus, quis aliquet justo rutrum id. Praesent porttitor tellus sit amet sem varius consectetur. Pellentesque ac libero commodo, pretium odio sed, vehicula dolor. Nullam at consectetur turpis, eget porta tortor. Aenean eu enim in dui aliquam blandit id at metus. Donec lobortis leo sed egestas mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi pulvinar justo odio, sed mollis nibh placerat at. Phasellus quis euismod dolor, eget mollis dui. 
                </p>
                <p>
                    <!-- ToDo: Am Ende kann hir auf eine extra seite verwiesen Werden -->
                    <a class="btn" href="#Feststand">Mehr dazu</a>
                </p><img src="http://lorempixel.com/140/140/animals" alt="Bsp. Bild 140x140" class="img-rounded" />
            </div>
            <div id="Gastrobetrieb" class="col-md-4 column">
                <h2>
                    Gastrobetrieb
                </h2>
                <p>
                    Was bringt den ABB-Lehrling dazu, jeden Abend nach Arbeitsschluss zu hämmern, zu sägen und zu schrauben, bis die Festbeiz steht? Warum opfern die Mitglieder des Quartiervereins Ferientage, um Theaterstücke einzuüben? Wie ist es möglich, dass eine Stadt mit 18.000 Einwohnern ein zehntägiges Fest auf die Beine stellt, mit 70 liebevollen Beizen und Hunderten von kulturellen Acts - ein Fest, das fast eine Millionen Menschen anziehen wird?
                </p>
                <p>
                    <!-- ToDo: Am Ende kann hir auf eine extra seite verwiesen Werden -->
                    <a class="btn" href="#Gastrobetrieb">Mehr dazu</a>
                </p><img src="http://lorempixel.com/140/140/nature" alt="Bsp. Bild 140x140" class="img-rounded" />
            </div>
        </div>
    </div>
</div>