<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="jumbotron">
				<h1>
					Badenfahrt Teilnehmer Portal
				</h1>
				<p>
                                    Kurz-Info zu den M&ouml;glichkeiten
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#info">Mehr Informationen</a>
				</p>
			</div>
		</div>
	</div>
        <div id="info" class="container">
	<div class="row clearfix">
		<div class="col-md-4 column">
			<h2>
				Festwirtschaft
			</h2>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pharetra nibh vel purus pretium, ut aliquam sem tincidunt. Quisque ut tempus lorem. Phasellus commodo mi at interdum placerat. Pellentesque ut nulla mauris. Vestibulum eu massa consectetur, porttitor magna quis, fringilla leo. Suspendisse tellus augue, tincidunt at ullamcorper vel, ornare in sem. Aliquam venenatis risus ex, sit amet laoreet libero viverra ac. Proin quis ligula in urna tempor rutrum. Nullam a dictum mauris, id eleifend nulla. In hac habitasse platea dictumst. Ut fermentum velit vel quam dignissim, in cursus turpis consectetur. Etiam vitae odio nec ligula vehicula maximus. 
			</p>
			<p>
				<a class="btn" href="#Festwirtschaft">Mehr dazu</a>
			</p><img src="http://lorempixel.com/140/140/cats" alt="Bsp. Bild 140x140" class="img-rounded" />
		</div>
		<div class="col-md-4 column">
			<h2>
				Feststand
			</h2>
			<p>
				 Quisque porttitor efficitur odio. Duis et magna nec nisi viverra congue. Curabitur sit amet pellentesque sapien. Quisque dictum ac diam vitae consectetur. Aliquam in diam pulvinar, malesuada sapien sit amet, aliquet orci. Integer et enim at dui scelerisque gravida ut vitae nisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam lacinia dui a mi cursus finibus quis eu ante. Curabitur id mi sit amet tellus feugiat cursus ac dictum risus. Vivamus dignissim eros sit amet commodo pulvinar. Morbi a euismod tellus. Praesent at venenatis dolor.
                        </p>
                        <p>
                                 Mauris gravida pulvinar risus, quis aliquet justo rutrum id. Praesent porttitor tellus sit amet sem varius consectetur. Pellentesque ac libero commodo, pretium odio sed, vehicula dolor. Nullam at consectetur turpis, eget porta tortor. Aenean eu enim in dui aliquam blandit id at metus. Donec lobortis leo sed egestas mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi pulvinar justo odio, sed mollis nibh placerat at. Phasellus quis euismod dolor, eget mollis dui. 
			</p>
			<p>
				<a class="btn" href="#Feststand">Mehr dazu</a>
			</p><img src="http://lorempixel.com/140/140/animals" alt="Bsp. Bild 140x140" class="img-rounded" />
		</div>
		<div class="col-md-4 column">
			<h2>
				Gastrobetrieb
			</h2>
			<p>
				Was bringt den ABB-Lehrling dazu, jeden Abend nach Arbeitsschluss zu hämmern, zu sägen und zu schrauben, bis die Festbeiz steht? Warum opfern die Mitglieder des Quartiervereins Ferientage, um Theaterstücke einzuüben? Wie ist es möglich, dass eine Stadt mit 18.000 Einwohnern ein zehntägiges Fest auf die Beine stellt, mit 70 liebevollen Beizen und Hunderten von kulturellen Acts - ein Fest, das fast eine Millionen Menschen anziehen wird?
			</p>
			<p>
				<a class="btn" href="#Gastrobetrieb">Mehr dazu</a>
			</p><img src="http://lorempixel.com/140/140/nature" alt="Bsp. Bild 140x140" class="img-rounded" />
		</div>
	</div>
        </div>
</div>