<h2>Registrieren</h2>

<?php if ($this->error): ?>
    <div class="alert alert-warning"> <!-- TODO: alert-error is not working -->
        <a class="close" data-dismiss="alert" href="#">×</a><?php echo $this->registrationError; ?>
    </div>
<?php endif ?>

<div class="row">
    <div class="col-xs-4">

        <?php
        $this->form->setAttribute('action', $this->url('user/register/personal'));
        $this->form->prepare();
        echo $this->form()->openTag($this->form);
        foreach ($this->form as $element)
        {
            if ($element instanceof Zend\Form\Element\Submit)
            {
                echo '<div>';
                $element->setAttribute('class', 'btn btn-primary');
            } else
            {
                echo '<div class="form-group">';
                $label = $element->getOption('label');
                echo $this->formLabel()->openTag() . $label . $this->formLabel()->closeTag();
                echo $this->formElementErrors($element);
                $element->setAttribute('class', 'form-control');
                $element->setAttribute('placeholder', $label);
            }
            echo $this->formElement($element);

            echo '</div>';
        }
        echo $this->form()->closeTag($this->form);
        ?>
    </div>
</div>